heat_template_version: 2015-04-30

description: A single Oracle 12cR1 database using ASM

parameters:
  public_net_id: 
    type: string
    default: 939b16fe-02a7-4437-a1e4-d26c6bc5929c
  private_net_id:
    type: string
    default: 31675bfc-fc1c-4c8f-a50b-ad51ccb7b3e0
  private_subnet_id:
    type: string
    default: 50ac042f-cc7a-4d77-a80e-ea7ce087d6b9
  security_group:
    type: string
    default: f9932fda-47f2-4afd-95b2-64b9d8557919

resources:

  server1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups: [{ get_param: security_group }]

  server1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: server1_port }


  oradb12:
    type: OS::Nova::Server
    properties:
      key_name: brian mac
      image: centos-7
      flavor: o.standard
      networks:
        - port: { get_resource: server1_port }

outputs:
  instance_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [oradb12, first_address] }
