heat_template_version: 2015-04-30

description: A single Oracle 12cR1 database using ASM

resources:

  single12cR1:
    type: OS::Nova::Server
    properties:
      key_name: server1-key
      image: CentOS-6-x86_64-GenericCloud
      flavor: m1.large
      user_data_format: RAW
      user_data:
        get_file: userdata-single12cR1
      networks: 
        - network: private

  ocrvote1:
    type: OS::Cinder::Volume
    properties:
      size: 5
      multiattach: True

  ocrvote2:
    type: OS::Cinder::Volume
    properties:
      size: 5

  ocrvote3:
    type: OS::Cinder::Volume
    properties:
      size: 5
  
  disk01:
    type: OS::Cinder::Volume
    properties:
      size: 10
  
  disk02:
    type: OS::Cinder::Volume
    properties:
      size: 10
  
  disk03:
    type: OS::Cinder::Volume
    properties:
      size: 10

  disk04:
    type: OS::Cinder::Volume
    properties:
      size: 10

  disk05:
    type: OS::Cinder::Volume
    properties:
      size: 10


  attach_ocrvote1:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: ocrvote1 }
       instance_uuid: { get_resource: single12cR1 }
  
  attach_ocrvote2:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: ocrvote2 }
       instance_uuid: { get_resource: single12cR1 }
  
  attach_ocrvote3:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: ocrvote3 }
       instance_uuid: { get_resource: single12cR1 }
  
  attach_disk01:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: disk01 }
       instance_uuid: { get_resource: single12cR1 }

  attach_disk02:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: disk02 }
       instance_uuid: { get_resource: single12cR1 }

  attach_disk03:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: disk03 }
       instance_uuid: { get_resource: single12cR1 }

  attach_disk04:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: disk04 }
       instance_uuid: { get_resource: single12cR1 }

  attach_disk05:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: disk05 }
       instance_uuid: { get_resource: single12cR1 }

outputs:
  instance_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [single12cR1, first_address] }
