heat_template_version: 2015-04-30

description: A single Oracle 12cR1 database using ASM

resources:

  single12cR1:
    type: OS::Nova::Server
    properties:
      key_name: server1-key
      image: CentOS-6-x86_64-GenericCloud
      flavor: m1.large
      user_data_format: RAW
      user_data:
        get_file: userdata-single12cR1
      networks: 
        - network: private

outputs:
  instance_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [single12cR1, first_address] }
