#!/bin/bash

sed -i " s/HOSTNAME=.*/HOSTNAME=single12cR1.thewoodruffs.org/g " /etc/sysconfig/network
#echo namserver 8.8.8.8 > /etc/resolv.conf
#echo nameserver 8.8.4.4 >> /etc/resolv.conf
#echo domain thewoodruffs.org >> /etc/resolv.conf
#echo search thewoodruffs.org >> /etc/resolv.conf

yum -y install https://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
yum -y install epel-release
yum -y install puppet dracut-modules-growroot cloud-utils-growpart iscsi-initiator-utils
chkconfig puppet on
chkconfig iptables off
chkconfig ip6tables off
sed -i " s/requiretty/\!requiretty/g " /etc/sudoers
/sbin/dracut -f -v > /tmp/dracut.log
#echo "`facter networking.interfaces.eth0.bindings.0.address` single12cR1.lab.thewoodruffs.org single12cR1" >> /etc/hosts
cloud-init single --name growpart

# Set up iSCSI
sed -i " s/#node.session.auth.authmethod = CHAP/node.session.auth.authmethod = CHAP/g " /etc/iscsi/iscsid.conf
sed -i " s/#node.session.auth.username.*/node.session.auth.username = single12cR1/g " /etc/iscsi/iscsid.conf
sed -i " s/#node.session.auth.password.*/node.session.auth.password = single12cR1wibble/g " /etc/iscsi/iscsid.conf
iscsiadm -m discovery -t sendtargets -p freenas01.thewoodruffs.org > /tmp/iscsi.log 2>&1
iscsiadm -m node --login >> /tmp/iscsi.log 2>&1


echo "SLEEPING 30 and REBOOTING"
echo "sleep 30 && reboot" > /tmp/go
nohup sh /tmp/go  &
