heat_template_version: 2015-04-30

description: An Oracle 12cR1 3 node RAC

resources:

  rac12cr11:
    type: OS::Nova::Server
    properties:
      key_name: server1-key
      image: CentOS-6-x86_64-GenericCloud
      flavor: m1.large
      networks: 
        - network: private

  rac12cr12:
    type: OS::Nova::Server
    properties:
      key_name: server1-key
      image: CentOS-6-x86_64-GenericCloud
      flavor: m1.large
      networks: 
        - network: private

  rac12cr13:
    type: OS::Nova::Server
    properties:
      key_name: server1-key
      image: CentOS-6-x86_64-GenericCloud
      flavor: m1.large
      networks: 
        - network: private

  ocrvote1:
    type: OS::Cinder::Volume
    properties:
      size: 5

  attach_ocrvote1_rac12cr11:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: ocrvote1 }
       instance_uuid: { get_resource: rac12cr11 }

  attach_ocrvote1_rac12cr12:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: ocrvote1 }
       instance_uuid: { get_resource: rac12cr12 }

  attach_ocrvote1_rac12cr13:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: ocrvote1 }
       instance_uuid: { get_resource: rac12cr13 }
  
outputs:
  instance_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [rac12cr11, first_address] }
